#!/bin/bash

TAR_FILE=$1; shift
PATCH_DIR=$1; shift
last_patch=$1; shift
THREADS=$1; shift

tar -x --strip-components=1 -f $TAR_FILE
../../apply_patches -d $PATCH_DIR -l $last_patch

[[ $? -ne 0 ]] && echo Patch $PATCH_NUM failed && exit 111

autoreconf

echo ./configure $*; echo

./configure $*
make -j$THREADS
