#!/bin/bash

# --enable-mem-check-log --enable-strict-config-checks

BUILD_OPTIONS="--enable-bfd --enable-snmp --enable-snmp-rfc --enable-dbus --enable-sha1 --enable-regex --enable-json"
DEBUG_OPTIONS="--enable-smtp-alert-debug --enable-epoll-debug --enable-epoll-thread-dump --enable-timer-check --enable-netlink-timers --enable-regex-debug --enable-tsm-debug --enable-regex-timers --enable-vrrp-fd-debug --enable-log-file --enable-asserts --enable-eintr-debug --enable-network-timestamp --enable-track-process-debug --enable-parser-debug --enable-dump-keywords"
MEMCHECK_OPTIONS="--enable-mem-check"
PERF_OPTIONS="--enable-perf"
LINK_DEBUG_OPTIONS="--disable-hardening --disable-optimise"
EINTR_DISABLE="--disable-eintr-debug"

OPTIONS=$BUILD_OPTIONS

while getopts ":hdeDf:mp-" opt; do
	case $opt in
		h)
			echo "$0 -- usage:"
			echo "	-h	Print this!"
			echo "	-d	enable debug options"
			echo "	-e	disable EINTR checking"
			echo "	-D	disable link optimiser/hardening"
			echo "	-f TYPE	make i/f type TYPE unchangeable"
			echo "	-m	enable mem-check"
			echo "	-p	enable perf"

			exit 0
			;;
		d)
			OPTIONS="$OPTIONS $DEBUG_OPTIONS"
			;;
		e)
			OPTIONS="$OPTIONS $EINTR_DISABLE"
			;;
		D)
			OPTIONS="$OPTIONS $LINK_DEBUG_OPTIONS"
			;;
		f)
			OPTIONS="$OPTIONS --with-fixed-if-type=$OPTARG"
			;;
		m)
			OPTIONS="$OPTIONS $MEMCHECK_OPTIONS"
			;;
		p)
			OPTIONS="$OPTIONS $PERF_OPTIONS"
			;;
		-)
			break
			;;
		?)
			echo Unknown option $OPTARG
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

./configure $OPTIONS $*
