#!/bin/bash

# --enable-mem-check-log --enable-strict-config-checks

BUILD_OPTIONS="--enable-bfd --enable-snmp --enable-snmp-rfc --enable-dbus --enable-sha1 --enable-regex --enable-json"
DEBUG_OPTIONS="--enable-debug"
ALL_DEBUG_OPTIONS="$DEBUG_OPTIONS --enable-genhash-debug --enable-one-process-debug"
OLD_COMMON_DEBUG_OPTIONS="--enable-asserts --enable-epoll-debug --enable-epoll-thread-dump --enable-eintr-debug --enable-parser-debug --enable-timer-check --enable-smtp-alert-debug --enable-smtp-connect-debug --enable-dump-keywords --enable-script-debug --enable-log-file"
OLD_VRRP_DEBUG_OPTIONS="--enable-vrrp-fd-debug --enable-tsm-debug --enable-track-process-debug --enable-checksum-debug --enable-netlink-timers --enable-network-timestamp"
OLD_LVS_DEBUG_OPTIONS="--enable-checker-debug --enable-regex-debug --enable-regex-timers"
OLD_DEBUG_OPTIONS="$OLD_COMMON_DEBUG_OPTIONS $OLD_VRRP_DEBUG_OPTIONS $OLD_LVS_DEBUG_OPTIONS"
MEMCHECK_OPTIONS="--enable-mem-check"
PERF_OPTIONS="--enable-perf"
LINK_DEBUG_OPTIONS="--disable-hardening --disable-optimise"
EINTR_DISABLE="--disable-eintr-debug"

OPTIONS=$BUILD_OPTIONS

# See if we need pre 2.0.20 debug options
VER=$(grep AC_INIT configure.ac | sed -e "s/[^]]*], \[//" -e "s/].*//" -e "s/\./ /g")
MAJOR=${VER%% *}
VER=${VER#* }
MINOR=${VER%% *}
REL=${VER#* }
[[ $MAJOR -lt 2 || ($MAJOR -eq 2 && $MINOR -eq 0 && $REL -lt 20) ]] && DEBUG_OPTIONS="$OLD_DEBUG_OPTIONS"

while getopts ":hadoeDf:cCmp-" opt; do
	case $opt in
		h)
			echo "$0 -- usage:"
			echo "	-h	Print this!"
			echo "	-a	enable all debug options"
			echo "	-d	enable standard debug options"
			echo "	-o	enable pre v2.0.20 debug options"
			echo "	-e	disable EINTR checking"
			echo "	-D	disable link optimiser/hardening"
			echo "	-f TYPE	make i/f type TYPE unchangeable"
			echo "	-m	enable mem-check"
			echo "	-p	enable perf"
			echo "	-c	enable strict cast alignment warnings"
			echo "	-C	enable cast alignment checks"

			exit 0
			;;
		a)
			OPTIONS="$OPTIONS $ALL_DEBUG_OPTIONS"
			;;
		d)
			OPTIONS="$OPTIONS $DEBUG_OPTIONS"
			;;
		o)
			DEBUG_OPTIONS="$OPTIONS $OLD_DEBUG_OPTIONS"
			;;
		e)
			OPTIONS="$OPTIONS $EINTR_DISABLE"
			;;
		D)
			OPTIONS="$OPTIONS $LINK_DEBUG_OPTIONS"
			;;
		f)
			OPTIONS="$OPTIONS --with-fixed-if-type=$OPTARG"
			;;
		m)
			OPTIONS="$OPTIONS $MEMCHECK_OPTIONS"
			;;
		p)
			OPTIONS="$OPTIONS $PERF_OPTIONS"
			;;
		c)
			OPTIONS="$OPTIONS --enable-strict-cast-align"
			;;
		C)
			OPTIONS="$OPTIONS --enable-cast-align-checks"
			;;
		-)
			break
			;;
		?)
			echo Unknown option $OPTARG
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

./configure $OPTIONS $*
