#!/bin/bash

last=$1
[[ $2 = del ]] && CMD=del || CMD=add
first=${3:-1}
iface=${4:-0}
iface_last=${5:-$iface}

for if in $(seq $iface $iface_last); do
	for i in $(seq $first $last); do
		ip -n low link $CMD link eth${if} bond${if}.$i type vlan id $i
		ip -n high link $CMD link eth${if} bond${if}.$i type vlan id $i
		if [[ $CMD = add ]]; then
			ip -n low link set bond${if}.$i up
			ip -n high link set bond${if}.$i up

			ip -n low addr add 100.${if}.$i.3/24 brd + dev bond${if}.$i
			ip -n high addr add 100.${if}.$i.1/24 brd + dev bond${if}.$i
		fi
	done
done
